#!/bin/sh
# feh --no-fehbg --bg-scale --no-xinerama --randomize /mnt/public/images/dual_monitor/* &
while read file
do
        case "$1" in
        "C-g")
                gimp "$file" ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-f")
                feh --bg-center "$file" ;;
        "C-h")
                hsetroot -center "$file" ;;
        "C-d")
                display -window root "$file" ;;
        "C-w")
               feh --no-fehbg --bg-scale --no-xinerama --randomize "$file" ;;
        esac
done