#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "$HOME/.Xmodmap"
xrdb -l "$HOME/.Xresources"

numlockx on &

# background and wallpaper
fbsetroot -solid "#333366" &
(sleep 2s && fbsetbg -c -r "$HOME/wallpaper/") &

# 3rd party apps
# (sleep 2s && conky -dc $HOME/.conky10fboxrc) &
# (sleep 2s && connman-gtk --tray) &

# polybar
(sleep 2s && "$HOME/bin/fluxbox-bar.sh")

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# exec fluxbox

# or if you want to keep a log:
exec fluxbox -log "$HOME/.fluxbox/log"
