#! /bin/sh

xsetroot -cursor_name left_ptr &

pgrep -x sxhkd > /dev/null || sxhkd &

bspwm-bar.sh &

# xsetroot -solid "#0E0F0F" &
feh --no-fehbg --bg-scale --no-xinerama --randomize /mnt/public/images/dual_monitor/* &

# picom -b &

bspc monitor HDMI1 -d 1 2 3 4 5
bspc monitor VGA1 -d 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          4
bspc config left_padding        4
bspc config right_padding       4
bspc config top_padding         24
bspc config bottom_padding      4

bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

bspc config pointer_modifier	mod1
bspc config click_to_focus	true
bspc configpointer_action1	move
bspc config pointer_action2	resize_side
bspc config pointer_action3	resize_corner

bspc desktop 3 -l monocle
bspc desktop 7 -l monocle

# Create a new rule.
# -a, --add (<class_name>|*)[:(<instance_name>|\*)[:(<name>|*)]] [*-o*|--one-shot] [monitor=MONITOR_SEL|desktop=DESKTOP_SEL|node=NODE_SEL] [state=STATE] [layer=LAYER] [split_dir=DIR] [split_ratio=RATIO] [(hidden|sticky|private|locked|marked|center|follow|manage|focus|border)=(on|off)] [rectangle=WxH+X+Y]

bspc rule -a Firefox desktop='^3' follow=on state=tiled
bspc rule -a Thunderbird desktop='^3' follow=on state=tiled
bspc rule -a Gimp desktop='^7' follow=on state=tiled
bspc rule -a Gimp-2.10 desktop='^7' follow=on state=tiled
bspc rule -a Vlc desktop='^9' follow=on  state=tiled
bspc rule -a Audacious desktop='^9' follow=on  state=floating
bspc rule -a Deadbeef desktop='^9' follow=on  state=floating
bspc rule -a Asunder desktop='^9' follow=on  state=floating
bspc rule -a XClock state=floating layer=below
bspc rule -a Xfce4-screenshooter state=floating
bspc rule -a Galculator state=floating
bspc rule -a feh state=floating
bspc rule -a Void_Exit_Session state=floating layer=above
bspc rule -a XCalc state=floating
bspc rule -a Xfce4-appfinder state=floating
bspc rule -a Xfce4-panel state=floating
bspc rule -a '*:libreoffice-writer' state=tiled
bspc rule -a '*:libreoffice-calc' state=tiled
bspc rule -a '*:libreoffice-startcenter' state=tiled
bspc rule -a libreoffice-* state=tiled
bspc rule -a Soffice state=tiled
bspc rule -a Yad state=floating layer=above
bspc rule -a Sxiv state=floating layer=above

bspc rule -a Gimp "Open Image" state=floating layer=above

bspc config normal_border_color     '#151517'
bspc config focused_border_color    '#34302F'
bspc config active_border_color     '#3A3A42'
bspc config presel_border_color     '#151517'
bspc config urgent_border_color     '#A52A2A'

bspc config active_locked_border_color      '#ff9e24'
bspc config focused_locked_border_color     '#ff9e24'
bspc config normal_locked_border_color      '#31aeff'
